FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY training/ ./training/
COPY models/ ./models/
COPY data/ ./data/

CMD ["python", "training/train_model.py"]
