# deployment/Dockerfile.grpc-web-proxy
FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY serving/go-server/ .
RUN go mod tidy
RUN go mod download
RUN go build -o grpc-web-proxy grpc-web-proxy.go

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /root/
COPY --from=builder /app/grpc-web-proxy .

EXPOSE 8081
CMD ["./grpc-web-proxy"] 